[tools]
flutter = "latest"
go = "latest"
java = "zulu-21"
node = "lts"
"npm:opencommit" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
perl = "latest"
pipx = "latest"
"pipx:ansible" = { version = "latest", pipx_args = "--include-deps" }
"pipx:speedtest-cli" = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
usage = "latest"
watchexec = "latest"

[alias]
flutter = "asdf:nyuyuyu/asdf-flutter"
