[tools]
flutter = "latest"
go = "latest"
java = "zulu-21"
node = "lts"
"npm:opencommit" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
perl = "latest"
pipx = "latest"
"pipx:ansible" = { version = "latest", pipx_args = "--include-deps" }
"pipx:speedtest-cli" = "latest"
python = "latest"
ruby = "latest"
rust = "stable"
usage = "latest"
watchexec = "latest"
aws-cli = "latest"
fastfetch = "latest"
github-cli = "latest"
ghq = "latest"
jq = "latest"
rclone = "latest"
shellcheck = "latest"
ripgrep = "latest"
"ubi:Genymobile/scrcpy" = "latest"
age = "latest"
chezmoi = "latest"
peco = "latest"
starship = "latest"
yt-dlp = "latest"
terraform = "latest"
xcodes = "latest"
gcloud = "latest"
